- name: Read switch
  include_role: { name: lgblkb, tasks_from: envise }
  vars: { input_file: "{{switch_info.value}}", set_to: "{{switch_info.key}}" }

- prepare_switch: { switch: "{{lookup('vars',switch_info.key)}}" }
  register: out
#- debug: msg="{{out.target_groups}}"
#- fail:
- name: Deploy targets
  include_role: { name: lgblkb, tasks_from: deploy_targets.yaml }
  loop_control: { loop_var: target_infos }
  loop: "{{out.target_groups}}"