- hosts: all
  vars:
    pull_project: yes
  roles:
    - lgblkb
  tasks:
    - name: INITIALIZE
      lgblkb_task:
        env_name: "{{env_name}}"
        settings_switch: '{{project_folder}}/provision/settings/switch.yaml'
        deploy_settings:
          - compose/infra.yaml
        vars:
          build_target: "{{build_target}}"
          infra_volumes_dir: "{{infra_volumes_dir}}"
          ansible_user_uid: "{{ansible_user_uid}}"
          ansible_user_gid: "{{ansible_user_gid}}"
          ansible_user_id: "{{ansible_user_id}}"
          project_folder: "{{project_folder}}"
      register: data
    #    - debug: msg="{{project_folder}}"
    #    - include_role: { name: lgblkb, tasks_from: new_base }
    #    - name: 'Create project networks'
    #      docker_network: "{{item}}"
    #      loop: "{{docker_infra.networks|default([])}}"
    - name: 'Create project networks'
      docker_network:
        name: "{{item}}"
      loop: "{{data.docker.infra.definition.networks|list}}"

    - file:
        path: "{{project_folder}}/provision/commands"
        mode: u=rwx,g=rx,o=rx
        #        owner: "{{ansible_user_id}}"
        recurse: yes
    - debug: msg="Project basement established!"
