- hosts: all
  roles:
    - name: base
  tasks:
    - include_tasks: { file: 'service_tasks/service.yaml' }
      vars: { service_options: "{{item}}" }
      loop:
        #        - name: yield_pred_trigger
        #          celery_worker:
        #
        #        - name: main
        #          command: python -m app.main
        #
        #        - name: meteo_scheduler
        #          command: python -m app.weather.scheduled_jobs
        #        - name: histogram_scheduler
        #          command: python -m app.histograms.scheduled_jobs
        #
        #        - name: histograms
        #          command: python -m app.histograms.histograms
        #
        #        - name: weather
        #          command: python -m app.weather.weather
        #
        #        - name: static_data
        #          command: python -m app.static_features.static_data
        #        - name: ph_data_generator
        #          command: python -m app.static_features.scheduled_jobs.ph
        #        - name: elevation_data_generator
        #          command: python -m app.static_features.scheduled_jobs.elevation
        #        - name: soil_data_generator
        #          command: python -m app.static_features.scheduled_jobs.soil
        #
        #        - name: collector
        #          command: python -m app.collector.collector

        - name: yield_predictor
          command: python -m app.predictor


    - name: Greetings!!!
      debug:
        msg: "Deployment successfull!!!"
