- hosts: all
  tasks:
    - include_role: { name: lgblkb, tasks_from: generate_ansible_secret }
      when: ansible_connection=='local'

    - include_role: { name: lgblkb, tasks_from: pull_project }
      when: ansible_connection!='local'

    - name: Install provision dependencies
      pip:
        requirements: "./files/.requirements.txt"
      when: ansible_connection!='local'

    - debug: msg="Project initialized!"