- hosts: localhost
  become: no
  roles:
    - name: base
      vars:
        run_default_tasks: no

  tasks:
    - name: Greetings
      debug:
        msg: "Project is initalized!!!"
#    - debug: msg="{{toml_data}}"

