- hosts: all
  become: no
  roles:
    - base

  tasks:
    - name: Build docker image
      shell:
        cmd: "{{project_tasks.docker_build}}"
        chdir:

#    - name: Docker run
#      docker_container:
#        name: "{{image_name}}"
#        image: "{{image_fullname}}"
#        hostname: "{{image_name}}"
#        env_file: "{{project_folder}}/.env"
#        env:
#          ENV_FOR_DYNACONF: "{{env_name}}"
#        comparisons:
#          '*': "strict"
#        volumes:
#          - "{{project_folder|quote}}:{{project_folder|quote}}"
#        working_dir: "{{project_folder|quote}}"
#        command: "sleep 1000"









