- hosts: all
  tasks:
    - name: Pull the project
      block:
        - name: Read project info
          manage_toml:
            path: "{{master_project_folder}}/pyproject.toml"
          register: master_toml_meta
          delegate_to: localhost

        - name: Pull from git
          git:
            repo: "{{master_toml_meta.out.tool.poetry.repository}}"
            dest: "{{project_folder}}"
            accept_hostkey: yes
            key_file: "~/.ssh/server_rsa"
            force: yes

    - name: Run base tasks
      import_role:
        name: base

    - name: Read secrets
      include_vars:
        file: "{{master_project_folder}}/provision/envs/{{env_name}}/.secrets.yaml"
        name: secrets

    - name: Build docker image
      shell: "{{project_tasks.docker_build}}"

    - name: Deploy docker containers
      include_role:
        name: base
        tasks_from: deployment.yaml









