- hosts: all
  vars:
    build_docker_image: yes
    show_container_details: no
    launch_container: yes
    pull_project: yes
  roles:
    - lgblkb
  tasks:
    - include_role: { name: lgblkb, tasks_from: pull_project }
      when: ansible_connection!='local'
    - name: INITIALIZE
      lgblkb_task:
        env_name: "{{env_name}}"
        settings_switch: 'settings/switch.yaml'
        deploy_settings:
          - compose/service.yaml
        vars:
          build_target: "{{build_target}}"
          project_folder: "{{project_folder}}"
          infra_volumes_dir: "{{infra_volumes_dir}}"
          ansible_user_uid: "{{ansible_user_uid}}"
          ansible_user_gid: "{{ansible_user_gid}}"
          ansible_user_id: "{{ansible_user_id}}"
      register: data

    - name: Build docker image
      shell: '{{project_folder}}/provision/commands/docker_build.sh'
      when: build_docker_image

    #    - debug: msg="{{data.compose}}"

    - docker_compose: "{{item.value}}"
      with_dict: "{{data.compose}}"
      loop_control:
        label: '{{item.key}}'


    - debug: msg="Deployment successfull!"
#    - debug: msg="{{data.compose}}"
#    - docker_compose: "{{item.value}}"
#      #    - debug:
#      #        msg: "{{item.value}}"
#      with_dict: "{{data.compose}}"
#      loop_control:
#        label: '{{item.key}}'
#
#    - debug: msg="Deployment successfull!"
