- hosts: all
  vars:
    build_docker_image: yes
    show_container_details: yes
    launch_container: no
  tasks:
    - include_role: { name: lgblkb, tasks_from: base }

    - name: Build docker image
      shell: "{{project_tasks.docker_build}}"
      when: build_docker_image

    - include_role: { name: lgblkb, tasks_from: deploy }
      loop_control: { loop_var: switch_info }
      with_dict:
        service_switch: deploy_switches/service.yaml

    - debug: msg="Deployment successfull!"
