all:
  hosts:
    production_server:
      ansible_host:
      ansible_user:
      ansible_python_interpreter: "/usr/bin/python3"
      become: no
  vars:
    env_name: "production"
    build_target: "production"
    project_folder:


