services:
  app:
    build: { }
    volumes:
      - '.:/project'
      - '${STORAGE}:/storage'
    environment: { }
    command: sleep infinity
    shm_size: "12gb"


#  db:
#    image: "postgres:15-bullseye"
#    restart: unless-stopped
#    environment:
#      POSTGRES_PASSWORD: '${PROJECT_NAME}'
#      POSTGRES_USER: '${PROJECT_NAME}'
#      POSTGRES_DB: '${PROJECT_NAME}'
#      TZ: "Asia/Almaty"
#    volumes:
#      - "${STORAGE_FOLDER}/${PROJECT_NAME}_pgdata:/var/lib/postgresql/data"
#    ports:
#      - "5432:5432"
