FROM mambaorg/micromamba:1-bullseye-slim as micromamba

# This is the image we are going add micromaba to:
FROM python:3.11-slim-bullseye as base

ARG USERNAME
ARG USER_ID
ARG GROUP_ID

ARG MAMBA_USER=${USERNAME}
ARG MAMBA_USER_ID=${USER_ID}
ARG MAMBA_USER_GID=${GROUP_ID}
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

COPY --from=micromamba "$MAMBA_EXE" "$MAMBA_EXE"
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh
COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh

RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
    /usr/local/bin/_dockerfile_setup_root_prefix.sh

USER $MAMBA_USER

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]
# Optional: if you want to customize the ENTRYPOINT and have a conda
# environment activated, then do this:
# ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "my_entrypoint_program"]

# You can modify the CMD statement as needed....
CMD ["/bin/bash"]

COPY lets.py.sh /home/$MAMBA_USER/.bash_completions/lets.py.sh
RUN echo 'source /home/lgblkb/.bash_completions/lets.py.sh' >> ~/.bashrc

ARG PROJECT_PATH
WORKDIR ${PROJECT_PATH}

#COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml .
#RUN micromamba install -y -v -f env.yaml && \
#    micromamba clean --all --yes
#
#ARG MAMBA_DOCKERFILE_ACTIVATE=1
