development:
  CELERY:
    config:
      accept_content:
      - json
      acks_on_failure_or_timeout: false
      broker_transport_options:
        visibility_timeout: 86400
      broker_url: redis://admin:emMz9GA4W9MBPsxS9SPzWY4HDhcHLg7Sk9Gjh39aF9FJYtvCb4ZtQztWJY8sfDnsRBcXThv7Eng268NyFVdwRVaGc7K5zU4RnJbgL4bqZpMnDQbT9cYxTvfhbUdb4jqDpRVXWp9wSzTNdJwtPdaMrpsbNSXQ5yp5hSRNMwR4gJxfSnc6RE8u2LrAgMkkJbA9ZYW4maNESZBP7ZVF5axLR2nuxyRaa7txNSfShqjyZ2XTJc59N8ZFSHzrmq2mULfDfmWTTDX8C5Dwe9W6gYBkSp6S4XNuMfzBRRUNDPxWbrNP7VmxdmGTWDNVMqkSvyHWFXEU48STDxj8xrmWKPxed8XcZ4tkHRJmQc7Jg68YnsCWXvunpnvdTGLnc6wbCjTh79rq62pKWnynaPLQK48GagG9vCMZufpyQRv5b9qDr22C385thcSnTzpfK8Zm5wCw8zMhPHTMBfvVe6EVAmkY6KLmp9Qf3ArC7Uh4dmdnjQ8bhhckNHp6UTcKHZpybjbU@192.168.1.8:6379
      enable_utc: true
      imports:
      - app.celery_tasks
      result_accept_content:
      - json
      result_backend: redis://admin:emMz9GA4W9MBPsxS9SPzWY4HDhcHLg7Sk9Gjh39aF9FJYtvCb4ZtQztWJY8sfDnsRBcXThv7Eng268NyFVdwRVaGc7K5zU4RnJbgL4bqZpMnDQbT9cYxTvfhbUdb4jqDpRVXWp9wSzTNdJwtPdaMrpsbNSXQ5yp5hSRNMwR4gJxfSnc6RE8u2LrAgMkkJbA9ZYW4maNESZBP7ZVF5axLR2nuxyRaa7txNSfShqjyZ2XTJc59N8ZFSHzrmq2mULfDfmWTTDX8C5Dwe9W6gYBkSp6S4XNuMfzBRRUNDPxWbrNP7VmxdmGTWDNVMqkSvyHWFXEU48STDxj8xrmWKPxed8XcZ4tkHRJmQc7Jg68YnsCWXvunpnvdTGLnc6wbCjTh79rq62pKWnynaPLQK48GagG9vCMZufpyQRv5b9qDr22C385thcSnTzpfK8Zm5wCw8zMhPHTMBfvVe6EVAmkY6KLmp9Qf3ArC7Uh4dmdnjQ8bhhckNHp6UTcKHZpybjbU@192.168.1.8:6379
      result_persistent: false
      result_serializer: json
      task_acks_late: false
      task_acks_on_failure_or_timeout: false
      task_always_eager: false
      task_create_missing_queues: true
      task_default_priority: 5
      task_ignore_result: false
      task_inherit_parent_priority: true
      task_queue_max_priority: 10
      task_remote_tracebacks: true
      task_send_sent_event: true
      task_serializer: json
      task_soft_time_limit: null
      task_time_limit: null
      task_track_started: true
      timezone: Asia/Almaty
      worker_concurrency: 1
      worker_max_tasks_per_child: 100
      worker_prefetch_multiplier: 1
      worker_send_task_events: true
    task_base_name: yield_pred
  POSTGIS_IMAGINATION:
    database: imagination
    host: 192.168.1.8
    password: admin123
    port: 5432
    user: admin
  POSTGIS_YIELD_PREDICTION:
    database: yield_prediction
    host: 192.168.1.8
    password: admin123
    port: 5433
    user: admin
  PROJECT:
    dirs:
      cache_folder: /home/lgblkb/caches/YieldPrediction/
      data_folder: /home/lgblkb/data/YieldPrediction/
      s2_storage_folder: /home/lgblkb/PycharmProjects/imagination/sentinel2
    wkt_geom: Polygon ((29.07090781880005181 37.57396591446815393, 141.57053978732929522
      37.57396591446815393, 141.57053978732929522 70.01110538979037301, 29.07090781880005181
      70.01110538979037301, 29.07090781880005181 37.57396591446815393))
  REDIS:
    host: 192.168.1.8
    password: emMz9GA4W9MBPsxS9SPzWY4HDhcHLg7Sk9Gjh39aF9FJYtvCb4ZtQztWJY8sfDnsRBcXThv7Eng268NyFVdwRVaGc7K5zU4RnJbgL4bqZpMnDQbT9cYxTvfhbUdb4jqDpRVXWp9wSzTNdJwtPdaMrpsbNSXQ5yp5hSRNMwR4gJxfSnc6RE8u2LrAgMkkJbA9ZYW4maNESZBP7ZVF5axLR2nuxyRaa7txNSfShqjyZ2XTJc59N8ZFSHzrmq2mULfDfmWTTDX8C5Dwe9W6gYBkSp6S4XNuMfzBRRUNDPxWbrNP7VmxdmGTWDNVMqkSvyHWFXEU48STDxj8xrmWKPxed8XcZ4tkHRJmQc7Jg68YnsCWXvunpnvdTGLnc6wbCjTh79rq62pKWnynaPLQK48GagG9vCMZufpyQRv5b9qDr22C385thcSnTzpfK8Zm5wCw8zMhPHTMBfvVe6EVAmkY6KLmp9Qf3ArC7Uh4dmdnjQ8bhhckNHp6UTcKHZpybjbU
    port: 6379
    username: admin
