- name: Run docker container
  docker_container:
    name: "{{image_name}}"
    hostname: "{{image_name}}"
    image: "{{image_fullname}}"
    env:
      ENV_FOR_DYNACONF: "{{env_name}}"
    comparisons:
      '*': "strict"
    volumes:
      - "{{project_folder}}:{{project_folder}}"
    working_dir: "{{project_folder}}"
    command: "sleep 1000"
    restart: yes