- name: Install provision dependencies
  pip:
    requirements: "{{project_folder}}/provision/.requirements.txt"

- name: Read project info
  manage_toml:
    path: "{{master_project_folder}}/pyproject.toml"
    copy_as:
      path: "{{master_project_folder}}/provision/.toml_info.yaml"
      method: to_yaml
  register: toml_meta
  delegate_to: localhost

- set_fact:
    project_info: "{{toml_meta.out.tool.poetry}}"
- set_fact:
    image_name: "{{project_info.name}}-{{env_name}}"
    image_tag: "{{project_info.version}}"
- set_fact:
    image_fullname: "{{project_info.name}}-{{env_name}}:{{project_info.version}}"

- include_vars:
    file: "{{toml_meta.copy_as.path}}"
    name: toml_data
- eval:
    expression: |
      for k,v in project_tasks.items():
        project_tasks[k]=" ".join(map(str.strip, v.splitlines())).strip()
    data:
      project_tasks: "{{toml_data.tool.project.tasks}}"
    out: project_tasks
  register: eval_meta
- set_fact:
    project_tasks: "{{eval_meta.project_tasks}}"

- name: Create project tasks
  manage_toml:
    path: "{{project_folder}}/pyproject.toml"
    data:
      tool:
        taskipy:
          tasks: "{{project_tasks}}"
  when: ansible_connection=='local'
