default:
  image: "${image_fullname}"
  environment:
    C_FORCE_ROOT: "1"
    GDAL_CACHEMAX: "256"
    NUMEXPR_MAX_THREADS: "8"

  networks: >-
    ${eval:
    "list(networks.keys())",
    "networks=docker.infra.definition.networks"
    }

  volumes: >-
    ${eval:
    "[':'.join([v] * 2) for v in volumes]",
    "volumes=
    list(settings['PROJECT']['dirs'].values())+
    [project_folder]
    "}

development:
  environment:
    TBOT_TOKEN: '5201739106:AAH0n4l5-NrlRXJ2mk4Y-nF-AKm54lUdf8Q'
    DATA_SOURCE_NAME: islamkhan_books
    MAX_VOTES: 25

production:
  volumes: >-
    ${eval:
    "[':'.join([v] * 2) for v in volumes]",
    "volumes=
    list(settings['PROJECT']['dirs'].values())
    "}