default:
  image: "${image_fullname}"
  env:
    ENV_FOR_DYNACONF: "${env_name}"
    C_FORCE_ROOT: "1"
    MPLCONFIGDIR: "${settings.PROJECT.dirs.cache_folder}"
    GDAL_CACHEMAX: "256"
    NUMEXPR_MAX_THREADS: "8"
  volumes: >-
    ${eval:
    "[':'.join([v] * 2) for v in volumes]",
    "volumes=
    list(settings['PROJECT']['dirs'].values())+
    [project_folder]
    "}
  working_dir: "${project_folder}"
  state: started
