default:
  image: "{{image_fullname}}"
  env:
    ENV_FOR_DYNACONF: "{{env_name}}"
    MPLCONFIGDIR: "{{service.PROJECT.dirs.cache_folder}}"
    GDAL_CACHEMAX: "2048"
    FLASK_APP: "app/server.py"
  volumes: >-
    {{"[folder+':'+folder for folder in set(list(dirs_info.values())+[project_folder])]"|
    eval(dirs_info=service.PROJECT.dirs,project_folder=project_folder)}}
  working_dir: "{{project_folder}}"
  state: started