default:
  PROJECT:
    name: "${project_name}"

  CELERY:
    config:
      accept_content: [ 'json' ]
      enable_utc: True
      timezone: "Asia/Almaty"
      task_acks_late: false
      task_create_missing_queues: true
      worker_cancel_long_running_tasks_on_connection_loss: true
      task_queue_max_priority: 10
      task_default_priority: 5
      task_inherit_parent_priority: True
      broker_url: "${fmt:'pyamqp://{user}:{password}@{hostname}',infra.RABBITMQ}"
      result_backend: "${fmt:'redis://:{password}@{host}:6379/0',infra.REDIS}"
      result_expires: 43200
      worker_prefetch_multiplier: 3
      worker_max_tasks_per_child: 3
      result_backend_transport_options: { visibility_timeout: 86400 }

development:
  PROJECT:
    dirs:
      cache_folder: "/storage/caches"
      data_folder: "/storage/data"

