all:
  hosts:
    staging_server:
      ansible_host:
      ansible_user:
      ansible_python_interpreter: "/usr/bin/python3"
      become: no
  vars:
    env_name: "staging"
    build_target: "builder"
    project_folder:


