volumes: &volumes >-
  {{"[folder+':'+folder for folder in set(list(dirs_info.values())+[project_folder])]"|
  eval(dirs_info=settings.PROJECT.dirs,project_folder=project_folder)}}

#    AIRFLOW__CELERY__FLOWER_HOST: localhost
#    AIRFLOW__CELERY__CELERY_CONFIG_OPTIONS:
#    AIRFLOW__CELERY__SYNC_PARALLELISM:
#    AIRFLOW__CELERY__FLOWER_PORT: "5555"
#        AIRFLOW__CELERY__FLOWER_BASIC_AUTH: "{{'{user}:{password}'|fmt(infra.RABBITMQ)}},patriot:ProektOsvobozhdenie369"
#    AIRFLOW__CELERY__FLOWER_BASIC_AUTH: admin:admin123


default:
  airflow_initdb:
    image: "{{image_fullname}}"
    name: airflow_initdb
    command: airflow initdb

  imagiflow_rabbitmq:
    image: "rabbitmq:3.8.9-management"
    name: "{{infra.RABBITMQ.hostname}}"
    env:
      RABBITMQ_DEFAULT_USER: "{{infra.RABBITMQ.user}}"
      RABBITMQ_DEFAULT_PASS: "{{infra.RABBITMQ.password}}"
    ports:
      - "15673:15672"

  imagiflow_flower:
    image: "gregsi/latest-celery-flower-docker"
    name: imagiflow_flower
    ports:
      - "5556:5555"
    env:
      FLOWER_PORT: "5555"
      AMQP_USERNAME: "{{infra.RABBITMQ.user}}"
      AMQP_PASSWORD: "{{infra.RABBITMQ.password}}"
      AMQP_HOST: "{{infra.RABBITMQ.hostname}}"
      AMQP_PORT: "{{infra.RABBITMQ.port}}"
      AMQP_ADMIN_USERNAME: "{{infra.RABBITMQ.user}}"
      AMQP_ADMIN_PASSWORD: "{{infra.RABBITMQ.password}}"
      AMQP_ADMIN_HOST: "{{infra.RABBITMQ.hostname}}"
      AMQP_ADMIN_PORT: "15673"
      FLOWER_MAX_TASKS: "36000"
      FLOWER_BASIC_AUTH: "{{infra.RABBITMQ.user}}:{{infra.RABBITMQ.password}}"

  airflow_webserver:
    image: "{{image_fullname}}"
    name: airflow_webserver
    command: airflow webserver
    ports:
      - "8080:8080"
    env:
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "Asia/Almaty"
    volumes: *volumes

  airflow_scheduler:
    image: "{{image_fullname}}"
    name: airflow_scheduler
    command: airflow scheduler
    volumes: *volumes
