default:
  imagiflow_flower:
    image: "gregsi/latest-celery-flower-docker:flower-0.9.4"
    name: imagiflow_flower
    ports:
      - "5556:5556"
    env:
      FLOWER_PORT: "5556"
      AMQP_USERNAME: "{{infra.RABBITMQ.user}}"
      AMQP_PASSWORD: "{{infra.RABBITMQ.password}}"
      AMQP_HOST: "{{infra.RABBITMQ.hostname}}"
      AMQP_PORT: "{{infra.RABBITMQ.port}}"
      AMQP_ADMIN_USERNAME: "{{infra.RABBITMQ.user}}"
      AMQP_ADMIN_PASSWORD: "{{infra.RABBITMQ.password}}"
      AMQP_ADMIN_HOST: "{{infra.RABBITMQ.hostname}}"
      AMQP_ADMIN_PORT: "15673"
      FLOWER_MAX_TASKS: "36000"
      FLOWER_BASIC_AUTH: "{{infra.RABBITMQ.user}}:{{infra.RABBITMQ.password}}"