default:
  CELERY:
    task_base_name: [ Not defined ]
    config:
      imports: [ 'app.celery_tasks' ]
      result_persistent: False
      task_acks_late: False
      task_acks_on_failure_or_timeout: False
      task_track_started: True
      enable_utc: True
      timezone: "Asia/Almaty"
      acks_on_failure_or_timeout: False
      worker_send_task_events: True
      task_send_sent_event: True
      task_inherit_parent_priority: True
      worker_prefetch_multiplier: 1
      worker_concurrency: 1
      worker_max_tasks_per_child: 100
      task_queue_max_priority: 10
      task_default_priority: 5
      task_create_missing_queues: True
      task_remote_tracebacks: True
      task_time_limit:
      task_soft_time_limit:
      task_ignore_result: False
      task_always_eager: False
      accept_content: [ 'json' ]
      result_accept_content: [ 'json' ]
      result_backend: &rb "{{'redis://{username}:{password}@{host}:{port}'|fmt(infra.REDIS)}}"
      broker_url: *rb
      task_serializer: 'json'
      result_serializer: 'json'
      broker_transport_options:
        visibility_timeout: 86400

development:
  PROJECT:
    dirs:
      cache_folder: "/home/lgblkb/caches/{{poetry_info.name}}"
      data_folder: "/home/lgblkb/data/{{poetry_info.name}}"

staging:
  PROJECT:
    dirs:
      cache_folder: "/mnt/md0/caches/{{poetry_info.name}}"
      data_folder: "/mnt/md0/data/{{poetry_info.name}}"

production:
  PROJECT:
    dirs:
      cache_folder: "/home/egistic_db/caches/{{poetry_info.name}}"
      data_folder: "/nfs/storage/data/{{poetry_info.name}}"




