default:
  pre: "{{docker.service}}"

  vars:
    name_prefix: "{{project_name}}"
    watchdog:
      all: yes
  configs:
    runner:
      command: python -m scripts.run
      state: present
      watchdog: { all: no }

