default:
  pre_: "${docker.infra}"
  definition:
    services:
      #      "*":
      #        pre_:
      #          networks: ${eval:"[k for k in docker.service.definition.networks]"}
      "*":
        pre_: "${docker.service}"
      islamkhan_books:
        command: ./lets.py prun app.app
        environment:
          TBOT_LINK: 'http://t.me/issai_books_bot'
          TBOT_TOKEN: '5249841111:AAGZru8n0c5qeZOjWKbKyYOqa0LeTO5MmaY'
          DATA_SOURCE_NAME: islamkhan_books
          MAX_VOTES: 25
      islamkhan_wiki:
        command: ./lets.py prun app.app
        environment:
          TBOT_LINK: 'http://t.me/issai_wiki_bot'
          TBOT_TOKEN: '5019313738:AAEEd8nu4X2dmWmFfeSQOFgInodZaJvytew'
          DATA_SOURCE_NAME: islamkhan_wiki
          MAX_VOTES: 25


#production:
#  definition:
#    services:
#      server:
#        command:
#        pdm run gunicorn solaichiki.main:app --bind 0:8000





