default:
  vars:
    name_prefix: "{{poetry_info.name}}"
    watchdog:
      all: yes

  pre: "{{docker_service}}"
  configs:
    tester:
      name: "tester"
      command: "python -m app"
      #      celery_worker:
      #        autoscale: 10,1
      state: started
      watchdog: yes





