all:
  hosts:
    egistic_db:
      ansible_host: 94.247.135.91
      ansible_user: egistic_db
      ansible_python_interpreter: "/usr/bin/python3.8"
      project_folder: [ Not defined ]
      key_file: "~/.ssh/lgblkb_rsa"
  vars:
    env_name: "production"
    build_target: 'builder'



