all:
  hosts:
    egistic_db:
      ansible_host: 94.247.135.91
      ansible_user: egistic_db
      ansible_python_interpreter: "/usr/bin/python3.8"
      project_folder: [ Not defined ]
  vars:
    env_name: "production"



