all:
  hosts:
    prod_server:
      ansible_host: <some_ip_address>
      ansible_user: ubuntu
      ansible_python_interpreter: "/usr/bin/python3"
      project_folder: <project_folder>
      key_file: "~/.ssh/<some_rsa_key>"
      infra_volumes_dir: "<infra_volumes_dir>"
  vars:
    env_name: "production"
    build_target: 'production'
    target_branch: master



