- name: Run base tasks
  include_role:
    name: base

- name: Build docker image
  shell: >-
    docker image build -t {{image_name}}:{{image_tag}}
    --target {{build_target}}
    --build-arg USER_ID={{ansible_user_uid}}
    --build-arg GROUP_ID={{ansible_user_gid}}
    --build-arg USERNAME={{ansible_user_id}}
    --build-arg PROJECT_DIR={{project_folder}}
    {{project_folder}}


#- name: Run docker container
#  shell: >-
#    docker container rm {{image_name}};
#    docker run
#    --detach
#    --name {{image_name}}
#    -v {{project_folder}}:{{project_folder}}
#    -w {{project_folder}}
#    --env-file {{project_folder}}/.env
#    {{image_name}}:{{image_tag}}
#    {{project_vars.cmd|default("cmd")}}
#
#- name: Create taskipy task
#  shell: |
#    python -c "import tomlkit
#    filename = '{{project_folder}}/pyproject.toml'
#    data = tomlkit.loads(open(filename).read())
#    tasks = data['tool']['taskipy']['tasks']
#    tasks['_ansible_task'] = 'docker attach {{image_name}}'
#    with open(filename, 'w') as file:
#       file.write(tomlkit.dumps(data))"