all:
  hosts:
    lgblkb_lab:
      ansible_host: 192.168.1.3
      ansible_user: lgblkb
      ansible_python_interpreter: "/usr/bin/python3"
      become: no
  vars:
    env_name: "staging"
    build_target: "builder"
    project_folder: "/home/lgblkb/tmp_project"

