all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/python3"
      become: no
  vars:
    env_name: "development"
    build_target: "builder"
    project_folder: "{{playbook_dir|dirname}}"

