all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/home/lgblkb/.cache/pypoetry/virtualenvs/boundary-detection-WsAl3N1O-py3.8/bin/python"
      project_folder: "{{playbook_dir|dirname}}"
  vars:
    env_name: "development"
    build_target: 'builder'
    infra_volumes_dir: "/storage/infra_volumes"




