all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/python3"
      project_folder: "{{playbook_dir|dirname}}"
  vars:
    env_name: "development"




