- name: "Setup redis"
  vars: &redis_vars
    redis_port: '6379'
    redis_name: 'redis'

  set_fact:
    <<: *redis_vars
    redis:
      name: "{{redis_name}}"
      expose: ["{{redis_port}}"]
      ports: ["{{redis_port}}:{{redis_port}}"]
      service_mounts:
        - source: "redis_data"
          target: "/data"
        - source: "redis_configs"
          target: "/usr/local/etc/redis"
      sysctls:
        net.core.somaxconn: "1024"
      command: ["redis-server", "--requirepass {{ secrets.redis.password }}"]

